server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.91.128:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  threads:
    virtual:
      enabled: true